### ISSUE TITLE
Publisher does not have permission for write document

### ISSUE THREAD

**Issue by detautama** [oddbit/tanam#165]
Publisher must have permission for write document, but it doesn't setting up on firestore rules and admin doesn't defined on firestore rules

Temporary solution already implemented to kumpul.id website
Changed on "allow write: if isManager()" to "allow write: if isPublisher()"
```
match /documents/{documentId} {
        allow read: if hasAnyRole();
        allow write: if isPublisher();
```

Changed on hasUserRole("manager") to hasUserRole("admin")
```
function isAtLeastManager() {
        return isOwner() || hasUserRole("admin");
      }
```

**Comment by DennisAlund** [comment]
Ya, I feel your pain. There is a confusion in the naming "manager" and "admin" that is being a bit inconsistently used.

I was thinking to rename the roles to: `superAdmin` and `admin` instead of `owner` and `admin` since it seems that "owner" isn't making it easy to remember if the other one was "manger" or "admin".

With the name "super admin" it will be easier to remember that the next one is just "admin"

**Comment by detautama** [comment]
So we will change and keep ?:
"owner" = "superAdmin"
"admin" keep as "admin"
