### ISSUE TITLE
Getting error error TS2307: Cannot find module 'tanam'.

### ISSUE THREAD

**Issue by beeman** [oddbit/tanam#20]
Hey! This project looks awesome, I'd love to play around with it.

It looks like there is an issue getting the minimal example to work though.

Repro steps: 
```
$ git clone https://github.com/oddbit/tanam
$ cd tanam/examples/minimal/functions
$ npm install
$ tsc
src/index.ts:2:24 - error TS2307: Cannot find module 'tanam'.

2 import * as tanam from 'tanam';
                         ~~~~~~~

src/index.ts:16:15 - error TS2307: Cannot find module 'tanam'.

16 export * from 'tanam';
                 ~~~~~~~
```

Any suggestions on how to fix this? I tried downloading this repo, compile it and use `npm link` but that gives the same error.

**Comment by DennisAlund** [comment]
Sorry a late reply. Christmas holidays came in between. The project was suffering from a lot of issues related to infrastructure and is being re-written in Angular to fix that. It will be using Angular instead of vue.

Please stay tuned for another week or two. The progress is on branch [`angular`](https://github.com/oddbit/tanam/tree/angular). I'll notify once that one is merged and help you to resolve this if the problem persists.

**Comment by beeman** [comment]
@DennisAlund thanks for the reply! Great to hear you're going to use Angular, it's my favorite front-end framework!

Looking forward to play with Tanam!

**Comment by DennisAlund** [comment]
Hi @beeman, this is long overdue. But we're finally on a pretty stable track using Angular for the CMS frontend. It took longer than we had planned as we discovered that Angular doesn't work well with building dynamic views on the fly. It turns out that the `Compiler` is only supported in development builds and does not work with Universal SSR. We ended up getting all the content client side rendered thanks to Universal engine magic.

So we're still using DustJS for now and there will be documentation coming up for how to write Dust themes and templates.

Please see the starter template project that has been created to test and showcase how to setup Tanam: https://github.com/oddbit/tanam-starter/


Please note this issue if you are trying it out: https://github.com/oddbit/tanam/issues/80
