### ISSUE TITLE
Move Inline SVG Code to Separate Files

### ISSUE THREAD

**Issue by DennisAlund** [oddbit/tanam#355]
## Context
The application contains several components with inline SVG code, which clutters the codebase and makes it harder to maintain. To improve the code structure and maintainability, all inline SVG code should be moved to dedicated SVG files in the `public` folder.

## Description
We need to refactor the codebase to move all inline SVG code into separate SVG files located in the `public` folder. This will involve creating a logical folder structure under `public/icons` to organize the icons and updating the code to reference these SVG files.

### Requirements

1. **Move Inline SVG Code to `public` Folder**:
   - Identify all occurrences of inline SVG code within the codebase.
   - Move each inline SVG to a dedicated SVG file in the `public/icons` folder.
   - Create logical subfolders under `public/icons` to organize the icons. For example, `hosting/src/components/Sidebar/icons/ArrowLeftIcon.tsx` should be moved to `public/icons/sidebar/arrow-left-icon.svg`.

2. **Update Code References**:
   - Update all code references to use the new SVG files from the `public` folder instead of the inline SVG code.

### Steps to Accomplish

1. **Global Search for Inline SVG Code**:
   - Perform a global search for the word "svg" (case insensitive, whole word match) to identify all occurrences of inline SVG code in the codebase.

2. **Move SVG Code to Files**:
   - For each identified inline SVG, create a corresponding SVG file in the `public/icons` folder.
   - Create logical subfolders under `public/icons` to categorize the icons based on their usage or location in the codebase.

3. **Update Code References**:
   - Replace the inline SVG code in the components with references to the new SVG files in the `public` folder.
   - Use the `Image` component from Next.js or standard `<img>` tags to include the SVG files in the components.

#### Before:

```tsx
// hosting/src/components/Sidebar/ArrowLeftIcon.tsx
const ArrowLeftIcon = () => (
  <svg width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M19 8.175H2.98748L9.36248 1.6875C9.69998 1.35 9.69998 0.825 9.36248 0.4875C9.02498 0.15 8.49998 0.15 8.16248 0.4875L0.399976 8.3625C0.0624756 8.7 0.0624756 9.225 0.399976 9.5625L8.16248 17.4375C8.31248 17.5875 8.53748 17.7 8.76248 17.7C8.98748 17.7 9.17498 17.625 9.36248 17.475C9.69998 17.1375 9.69998 16.6125 9.36248 16.275L3.02498 9.8625H19C19.45 9.8625 19.825 9.4875 19.825 9.0375C19.825 8.55 19.45 8.175 19 8.175Z" fill="" />
  </svg>
);
```

#### After:

**1. Move the SVG code to `public/icons/sidebar/arrow-left-icon.svg`:**
```xml
<!-- public/icons/sidebar/arrow-left-icon.svg -->
<svg width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M19 8.175H2.98748L9.36248 1.6875C9.69998 1.35 9.69998 0.825 9.36248 0.4875C9.02498 0.15 8.49998 0.15 8.16248 0.4875L0.399976 8.3625C0.0624756 8.7 0.0624756 9.225 0.399976 9.5625L8.16248 17.4375C8.31248 17.5875 8.53748 17.7 8.76248 17.7C8.98748 17.7 9.17498 17.625 9.36248 17.475C9.69998 17.1375 9.69998 16.6125 9.36248 16.275L3.02498 9.8625H19C19.45 9.8625 19.825 9.4875 19.825 9.0375C19.825 8.55 19.45 8.175 19 8.175Z" fill="" />
</svg>
```

**2. Update the component to reference the SVG file:**
```tsx
// hosting/src/components/Sidebar/ArrowLeftIcon.tsx
import Image from 'next/image';

const ArrowLeftIcon = () => (
  <Image src="/icons/sidebar/arrow-left-icon.svg" alt="Arrow Left" width={20} height={18} />
);
```

### Acceptance Criteria

- All inline SVG code has been moved to separate SVG files in the public/icons folder.
- Logical subfolders are created under public/icons to categorize the icons.
- All components are updated to reference the new SVG files.
- The application works as expected without any broken icons.

**Comment by WidaSuryani** [comment]
Hallo @DennisAlund , I've partiality done to move inline `svg` to a separate file, but along the way, I encountered a couple of issues which is related to customizing `svg` itself, so here are the issues:

## Issues

1. It is hard to make the `svg` reusable because when we have different colors, we need to make a new file for each color
2. Still related to 1st point, I see a lot of our implementation that we put a className on `svg` itself,  for example: changing the color on the hover or changing the color on the dark theme, we couldn’t do it on an image tag
3. Changing the size is also quite tricky sometimes
4. We need to make sure that `svg` is optimized


## Proposed Solutions
Based on these problems, I propose a solution where we use a class-based icon with [this library](https://github.com/egoist/tailwindcss-icons). Here are the benefits:
1. It is natively built for Tailwind so it's easier for us to use it
1. We can choose from a lot of icon options. Not just a lot of icon options, but we can combine more than one icon set, for example, we can combine icons from MDI icons, Lucide icons, and many more. You can see the icon set options here: https://icon-sets.iconify.design/
1. It's easier for us to customize the color, size, etc, since it uses Tailwind
1. Well-optimized library, because in the build process, it will automatically compile only the icon that we use
1. If we even need a custom icon that doesn’t exist on the icon sets, then we can easily add it
1. We can remove all of the icon files from our source code


if you agree, I will implement all of the icons with this solution :)
If you not , I will continue moving the rest of the `svg` file ✌️

**Comment by DennisAlund** [comment]
Perfect suggestion @WidaSuryani  go for that solution and exchange what you find with Google Material icons 🙏
